version: '2'
services:
    app:
        image: alpine:3.7
        ports:
            - 3030:3030
            - 3031:3031
            - 3032:3000
            - 9229:9229
        volumes:
            - ./:/app
        working_dir: /app
        command:
            - sh
            - -c
            - apk add --no-cache nodejs mediainfo yarn && yarn install && yarn run debug
